Jayus/Jayus/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.site.index_template = 'admin/my_custom_index.html'
admin.site.app_index_template = 'admin/my_custom_app_index.html'
admin.autodiscover()
#from JayusApp.admin import admin_site

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    # admin
    #url(r'^myadmin/', include(admin_site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    # rich textbox
    url(r'^ckeditor/', include('ckeditor.urls')),

    # urls al home
    url(r'^$', 'JayusApp.views.home', name='home'),
    url(r'^/', 'JayusApp.views.home'),
    url(r'^home/', 'JayusApp.views.home'),

    # registrar/validar
    url(r'^registrar/', 'JayusApp.views.registrar'),
    url(r'^validar/(?P<id>[^/]+)', 'JayusApp.views.validar'),
    url(r'^validar/', 'JayusApp.views.validar'),

    # funcionales
    url(r'^perfil/(?P<idPerfil>[^/]+)', 'JayusApp.views.perfilView'),
    url(r'^perfil/', 'JayusApp.views.perfilView'),
    url(r'^comunidad/(?P<idComunidad>[^/]+)', 'JayusApp.views.comunidad'),
    url(r'^mis_comunidades/', 'JayusApp.views.mis_comunidades'),

    # statics
    url(r'^aboutUs/', 'JayusApp.views.aboutUs'),
    url(r'^gracias/', 'JayusApp.views.gracias'),

    # contenido
    url(r'^contenido/(?P<idContenido>[0-9]+)', 'JayusApp.views.contenido'),
    url(r'^contenido/', 'JayusApp.views.contenido'),
    url(r'^contenido_add/(?P<lugar>\w+)/(?P<idLugar>\w+)', 'JayusApp.views.contenido_add'),
    url(r'^contenido_add/', 'JayusApp.views.contenido_add'),
    url(r'^alta_comentario/(?P<idContenido>[0-9]+)', 'JayusApp.views.alta_comentario'),
]

#http://127.0.0.1:8000/validar?id=df7e4f22-f0fe-11e4-bb07-000c293f080b
#http://127.0.0.1:8000/contenido?idcontenido=1

Jayus/JayusApp/models.py
# -*- coding: utf-8 -*-
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import Group
#from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from JayusApp.Common.Enum import SexoEnum, VisibilidadEnum, TipoContenidoEnum
from JayusApp.Common.Enum import EstadoContenidoEnum, EstadoMiembroEnum
from JayusApp.Common.Enum import RolMiembroEnum
# TODO: https://docs.djangoproject.com/en/1.8/topics/auth/default/#topic-authorization


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password):
        if not username:
            raise ValueError('Se requiere nombre de usuario')

        if not email:
            raise ValueError('Se requiere email')

        if not password:
            raise ValueError('Se requiere contraseña')

        user = self.model(
            username=username,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email,
            password=password
        )
        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=50,
        verbose_name='Nombre de usuario',
        unique=True)
    email = models.EmailField(
        verbose_name='Correo electrónico',
        max_length=100
    )
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    groups = models.ForeignKey(Group)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):              # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

# Create your models here.


class RegistrosPendientes(models.Model):
    token = models.CharField(max_length=64, verbose_name="Activation key",
                                default=uuid.uuid1)
    usuario_modificacion = models.ForeignKey(CustomUser, null=True,
                                            blank=True)
    fecha_generacion = models.DateField(default=timezone.now)
    es_valido = models.BooleanField(default=True)


class auditoriaField(models.Model):
    fecha_modificacion = models.DateField(default=timezone.now)
    usuario_modificacion = models.CharField(max_length=100, null=True,
                                            blank=True)
    # Está clase usa herencia para las tablas que necesitan auditoria.
    # No construye ninguna clase, pero las que la heredan tienen estos campos

    class Meta:
        abstract = True


class Perfil(models.Model):
    usuario = models.OneToOneField(CustomUser)
    imagen = models.ImageField(null=False,
                    default="http://localhost:8000/static/img/users.png")
    nombre = models.CharField(max_length=100, null=True, blank=True)
    apellido = models.CharField(max_length=100, null=True, blank=True)
    fechaNacimiento = models.DateField(default=timezone.now)
    sexo = models.CharField(max_length=1, choices=SexoEnum.choices(),
                        null=True, blank=True)
    localidad = models.CharField(blank=True, max_length=30)
    provincia = models.CharField(blank=True, max_length=30)
    pais = models.CharField(blank=True, max_length=30)
    telefono = models.CharField(blank=True, max_length=30)

    def __str__(self):
        # Ver si no hay nombre/apellido entonces user name
        return (self.usuario.username)

    def save(self, *args, **kwargs):
        if not self.usuario:
            raise ValueError('Se requiere usuario')

        # Saving the object with the default save() function
        super(Perfil, self).save(*args, **kwargs)


class Comunidad(models.Model):
    nombre = models.CharField(max_length=80, default="Test")
    descripcion = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nombre


class Miembro(auditoriaField):
    comunidad = models.ForeignKey(Comunidad, null=False, blank=False)
    usuario = models.ForeignKey(CustomUser, null=False, blank=False)
    rol = models.CharField(max_length=1, choices=RolMiembroEnum.choices(),
                                default=RolMiembroEnum.Publicador.value)
    estado = models.CharField(max_length=1, choices=EstadoMiembroEnum.choices(),
                                default=EstadoMiembroEnum.Activo.value)

    def __str__(self):
        return ""


class Contenido(auditoriaField):
    titulo = models.CharField(max_length=100)
    contenido = RichTextField()
    estado = models.CharField(max_length=1,
                            choices=EstadoContenidoEnum.choices(),
                            default=EstadoContenidoEnum.Activo.value)
    visibilidad = models.CharField(max_length=1,
                            choices=VisibilidadEnum.choices(),
                            default=VisibilidadEnum.Privado.value)
    comunidad = models.ForeignKey(Comunidad, null=True, blank=True)
    usuario = models.ForeignKey(CustomUser, null=True, blank=True,
                related_name='usuario_creador_contenido')


class DetalleContenido(auditoriaField):
    contenido = models.ForeignKey(Contenido, null=False, blank=False)
    descripcion = models.CharField(max_length=250)
    usuario = models.ForeignKey(CustomUser, null=False,
                related_name='usuario_creador_detalle')
    tipo_contenido = models.CharField(max_length=1,
                                    choices=TipoContenidoEnum.choices(),
                                    default=TipoContenidoEnum.Comentario.value)

Jayus/JayusApp/forms/commentForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Contenido, DetalleContenido


class NewCommentForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.Textarea, label='Comentario',
                        max_length=250, required=True)

    class Meta:
        model = DetalleContenido
        fields = ('descripcion',)

    def clean_comment(self):
        # Chequea que el comentario no esté vacío
        comentario = self.cleaned_data.get("descripcion")

        if comentario != "":
            raise forms.ValidationError("No puede insertar un comentario vacío.")
        return comentario

Jayus/JayusApp/forms/contenidoForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Contenido
from ckeditor.widgets import CKEditorWidget


class ContenidoForm(forms.ModelForm):
    titulo = forms.CharField(label='Título', max_length=100,
                        required=True)
    contenido = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Contenido
        fields = ('titulo', 'contenido', 'visibilidad')

Jayus/JayusApp/views.py
# -*- coding: utf-8 -*-
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
#from django.contrib import admin
from JayusApp.Common.Enum import VisibilidadEnum
from JayusApp.models import RegistrosPendientes, Contenido, DetalleContenido
from JayusApp.models import Perfil, Comunidad, Miembro
from JayusApp.forms.userForm import UserCreationForm, RegistrosPendientesForm
from JayusApp.forms.contenidoForm import ContenidoForm
from JayusApp.forms.commentForm import NewCommentForm
from JayusApp.consultas.consultasComunidad import comunidad_por_user
# Create your views here.


def home(request):
    if not request.user.is_authenticated():
        content_list = Contenido.objects.filter(visibilidad=VisibilidadEnum.Publico.value)
    else:
        content_list = Contenido.objects.all()
    return render(request, 'home.html', {'content_list': content_list})


def gracias(request):
    return render(request, 'gracias.html')


def aboutUs(request):
    return render(request, 'aboutUs.html')


def registrar(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            username = form['username'].value()
            email = form['email'].value()
            usuario = form.save()

            data = {'usuario_modificacion': usuario.id,
                'es_valido': True}
            user_validation = RegistrosPendientesForm(data)
            user_validation.is_valid()
            a_validar = user_validation.save()

            subject = 'Alta usuario'
            message = "Bienvenido a Jayus. \n Gracias por registrarte " + username + ". \n. "
            message += "Para validar, por favor ingrese al siguiente link: "
            message += "http://localhost:8000/validar?id=" + str(a_validar.token)
            sender = 'JayusApp@hotmail.com'
            recipients = [email]

            send_mail(subject, message, sender, recipients, fail_silently=False)
            return HttpResponseRedirect('/gracias')
        else:
            return render(request, 'registrar_user.html', {'form': form})
            #return render(request, 'admin/404.html')
    else:
        if request.user.is_authenticated():
            return HttpResponseRedirect('/home')
        else:
            form = UserCreationForm()
            return render(request, 'registrar_user.html', {'form': form})


def validar(request, id=''):
    if request.method == 'POST':
        if (id != ''):
            user = RegistrosPendientes.objects.filter(token = id).first().usuario_modificacion
            user.is_active = True
            user.is_admin = True
            user.save()

            g = Group.objects.get(name='Novato')
            g.user_set.add(user)

            # Sirve para probar: (Hay que comentar la creación de perfil)
            #http://localhost:8000/validar/?id=1a4753ec-f208-11e4-bbeb-000c29f93b19

            #Crear perfil
            perfil = Perfil()
            perfil.usuario = user
            perfil.save()

            return HttpResponseRedirect('/perfil/' + str(perfil.id))
        else:
            # TODO: Ver es muy fácil sobre escribir
            return render(request, 'admin/404.html')
    else:
        token_recibido = request.GET.get('id', '')
        context = {'id': token_recibido}
        return render(request, 'validar_user.html', context)


@login_required
def perfilView(request, idPerfil=''):
    if (idPerfil != ''):
        query = Perfil.objects.filter(id=idPerfil).first()
        if (query is not None):
            form = {
                'idPerfil': idPerfil,
                'perfil': query,
                'usuario': query.usuario,
                'content_list': Contenido.objects.filter(usuario=query.usuario),
            }
            return render(request, 'perfil.html', form)
        else:
            return render(request, 'admin/404.html')
    else:
        query = Perfil.objects.filter(usuario=request.user.id).first()
        form = {
            'idPerfil': query.id,
            'perfil': query,
            'usuario': request.user,
            'content_list': Contenido.objects.filter(usuario=request.user.id),
        }
        return render(request, 'perfil.html', form)


@login_required
def mis_comunidades(request):
    form = {
        'mis_comunidades': comunidad_por_user(request.user)
    }
    return render(request, 'mis_comunidades.html', form)


@login_required
def comunidad(request, idComunidad):
    if (idComunidad != ''):
        query = Comunidad.objects.filter(id=idComunidad).first()
        if (query is not None):
            if Miembro.objects.filter(comunidad=idComunidad,
                    usuario=request.user.id):
                form = {
                    'idComunidad': idComunidad,
                    'comunidad': query,
                    'content_list': Contenido.objects.filter(comunidad=idComunidad),
                    }
                return render(request, 'comunidad.html', form)

    return render(request, 'admin/404.html')


@login_required
def alta_comentario(request, idContenido):
    if request.method == 'POST':
        if (idContenido is not None):
            form = NewCommentForm(request.POST)
            if form.is_valid():
                obj = DetalleContenido()
                obj.contenido = Contenido.objects.filter(id=idContenido).first()
                obj.descripcion = form['descripcion'].value()
                obj.usuario = request.user
                obj.usuario_modificacion = request.user
                obj.save()
                return HttpResponseRedirect('/contenido/' + str(idContenido))
    return render(request, 'alta_comentario.html', { 'idContenido' : idContenido})


@login_required
def contenido(request, idContenido):
    if (idContenido != 0):
        form = {
            'contenido': Contenido.objects.filter(id=idContenido).first(),
            'formContenido': NewCommentForm,
            'comentarios': DetalleContenido.objects.filter(contenido=idContenido)
            }

        return render(request, 'contenido.html', form)
    return render(request, 'admin/404.html')


# Tipo: Perfil o Comunidad
@login_required
def contenido_add(request, lugar='', idLugar=''):
    form = ContenidoForm()
    if request.method == 'POST':
        form = ContenidoForm(request.POST)
        if form.is_valid():
            obj = Contenido()
            obj.titulo = form['titulo'].value()
            obj.contenido = form['contenido'].value()
            obj.visibilidad = form['visibilidad'].value()
            obj.usuario_modificacion = request.user
            if (lugar == 'perfil'):
                obj.usuario = request.user
                obj.save()
                return HttpResponseRedirect('/perfil')
            else:
                obj.comunidad = Comunidad.objects.filter(id=idLugar).first()
                obj.save()
                return HttpResponseRedirect('/comunidad/' + str(idLugar))
    # Si no se fue ya entonces ver q devuelvo
    if (lugar is not None):
        if (lugar == 'perfil' or idLugar is None):
            obj = Perfil.objects.filter(usuario=request.user.id).first()
            if (obj is None):
                #Crear perfil si no existe
                perfil = Perfil()
                perfil.usuario = request.user
                perfil.save()

            context = {
                'form': form,
                'lugar': lugar,
                'nombre': obj.usuario.username,
                'idLugar': idLugar
                }
            return render(request, 'contenido_add.html', context)

        elif (lugar == 'comunidad' and idLugar is not None):
            obj = Comunidad.objects.filter(id=idLugar).first()
            if (obj is not None):
                context = {
                'form': form,
                'lugar': lugar,
                'nombre': obj.nombre,
                'idLugar': idLugar
                }
            return render(request, 'contenido_add.html', context)
    return render(request, 'admin/404.html')

Jayus/JayusApp/templates/aboutUs.html
{% extends "admin/my_custom_index.html" %}

{% block content %}
    <h1>Sobre Nosotros</h1>

    <div class="row">
        <div class="col-sm-4"><img src="../static/img/Lucas.jpg" class="foto-perfil"></div>
        <div class="col-sm-4"><img src="../static/img/Nati.jpg" class="foto-perfil"></div>
        <div class="col-sm-4"><img src="../static/img/Mariano.jpg" class="foto-perfil"></div>
    </div>
    <div class="row">
        <div class="col-sm-4"><b>Lucas Betolini</b></div>
        <div class="col-sm-4"><b>Natalí Vargas</b></div>
        <div class="col-sm-4"><b>Mariano Schaberger</b></div>
    </div>
    <div class="row" style="padding:2%">
        <br>
        <p>Con la expectativa de poder crear
        un software sencillo y práctico, que pueda
        de una manera simple incorporarse y ponerse
        en funcionamiento, es que surge Jayus.</p>
        <br>
        <p>El sistema fue desarrollado inicialmente
        para cumplir con obligaciones universitarias,
        luego dimos cuenta de sus potenciales
        posibilidades de competir en el mercado de
        los gestores de contenido, principalmente
        por dos ventajas fundamentales:</p>
        <ui>
        <li><b>Simpleza</b>, se busca no tener una gran cantidad
        de opciones y configuraciones que
        distraigan a los usuarios.</li>
        <li><b>Libertad</b>, para permitir a los usuarios
        tomar el código, usarlo y modificarlo a
        gusto.</li>
        <br>
        <p>Primordialmente buscamos poder crecer
        en este mercado apuntando y basando
        nuestro desarrollo para contribuir a
        pequeñas y medianas empresas.</p>
        <br>
        <p>Por último queremos informarles que
        pueden contactarse con nosotros a través
        de la dirección de correo electrónico:
        Jayus@hotmail.com</p>
    </div>

{% endblock content %}

Jayus/JayusApp/templates/alta_comentario.html
<left style="width:100%; margin: 0 auto !important;">
    <div class="panel panel-primary" style="padding:1%">
        <div class="panel-body">
        <form action="{% url 'JayusApp.views.alta_comentario' idContenido%}" method="post">
            {% csrf_token %}
            <div class="row">
                <textarea class="form-control" rows="5" id="id_descripcion"
                name="descripcion" type="text" placeholder="Comentar..."
                required></textarea>
            </div>
            <div class="row">
                {{ formComentario.descripcion.errors }}
            </div>
            <div class="row">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>
            <div class="row" style="padding:2%">
                <button class="btn btn-primary" type="submit">Comentar</button>
            </div>
        </form>
      </div>
    </div>
</left>

Jayus/JayusApp/templates/comentarios.html
{% extends "contenido.html" %}
{% block content %}
    <h3>Alta comentarios...</h3>
{% endblock %}

Jayus/JayusApp/templates/comunidad.html
{% extends "admin/my_custom_index.html" %}
{% load admin_urls %}

{% block title %}Jayus | Comunidad {{comunidad.nombre}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-5 col-md-offset-1">
            <h2>{{ comunidad.nombre }}</h2>
            <p>{{ comunidad.descripcion }}</p>
        </div>
        <div class="col-md-2 col-md-offset-4">
            <div class="row" style="padding: 2%">
                <a href="{% url 'JayusApp.views.contenido_add' 'comunidad' comunidad.id %}">
                    Crear contenido
                </a>
            </div>
            <div class="row" style="padding: 2%">
                <a href="{% url 'admin:JayusApp_comunidad_change' comunidad.id %}">
                    Editar comunidad
                </a>
            </div>
<!--
            <div class="row" style="padding: 2%">
                <a href="{% url 'JayusApp.views.comunidad' comunidad.id %}">
                    Miembros
                </a>
            </div>
-->
        </div>
    </div>
    <hr>

    {% for contenido in content_list %}
        <div class="list-group">
          <a href="{% url 'JayusApp.views.contenido' contenido.id %}" class="list-group-item deactive">
            <h4 class="list-group-item-heading">{{ contenido.titulo|safe }}</h4>
            <p class="list-group-item-text">{{ contenido.contenido|safe }}</p>
          </a>
        </div>
    {% endfor %}
{% endblock %}

Jayus/JayusApp/templates/contenido.html
{% extends "admin/my_custom_index.html" %}
{% load admin_urls %}

{% block title %}Jayus | {{contenido.titulo}}{% endblock %}

{% block content %}
    <h1>{{contenido.titulo}}</h1>
    <p>{{contenido.contenido|safe}}</p>

    {% if comentarios %}
        <div class="panel panel-default">
            <div class="list-group-item list-group-item-info">Comentarios</div>
                <ul class="list-group">
                  {% for comentario in comentarios %}
                        <li class="list-group-item">
                            <p>Creado por <strong>{{comentario.usuario_modificacion}} </strong> el {{comentario.fecha_modificacion}}</p>
                            <p>{{comentario.descripcion}}</p>
                        </li>
                  {% endfor %}
                </ul>
        </div>
    {% endif %}

    {% include "alta_comentario.html" with idContenido=contenido.id formComentario=formContenido %}
{% endblock %}

Jayus/JayusApp/templates/contenido_add.html
{% extends "admin/my_custom_index.html" %}
{% load staticfiles %}

{% block content %}

<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script>
    CKEDITOR.replace('id_contenido');
</script>

<form action="{% url 'JayusApp.views.contenido_add' lugar idLugar %}" method="post"  style="padding:2%;">
    {% csrf_token %}

    <div class="alert alert-info" role="alert">
      <a href="#" class="alert-link">
            Creando contenido en <strong>{{lugar}}</strong>: {{nombre}}
      </a>
    </div>
    <br>
    <div class="form-inline row">
        <div class="form-group col-md-6">
            <label for="id_titulo">Título: </label>
            {{ form.titulo }}
            {{ form.titulo.errors }}
        </div>
        <div class="form-group  col-md-6">
            <label for="id_visibilidad">Visibilidad: </label>
            {{ form.visibilidad }}
        </div>
    </div>
    <div class="form-group row" style="padding:2%;">
            <label for="id_contenido">Contenido</label>
            <textarea class="ckeditor" id="id_contenido" name="contenido"></textarea>
    </div>
    <div class="row">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

    <center class="row" style="padding:2%">
        <button class="btn btn-primary" type="submit">Guardar</button>
        <a class="btn btn-default" href="{% url 'JayusApp.views.home' %}"">Cancelar </a>
    </center>
</form>

{% endblock content %}

Jayus/JayusApp/templates/gracias.html
{% extends "admin/my_custom_index.html" %}
{% block content %}
    <h1>Gracias por registrarse!</h1>


    <p>En el caso de no haber recibido el
    mail con la confirmación de su registro, revise
    su carpeta de correos no deseados.</p>
    <br>

{% endblock content %}
</html>

Jayus/JayusApp/templates/home.html
{% extends "admin/my_custom_index.html" %}

{% block title %}Jayus | Home{% endblock %}

{% block content %}
<h2>Portal de Contenido</h2>

{% for contenido in content_list %}
    <div class="list-group">
        <a href="{% url 'JayusApp.views.contenido' contenido.id%}" class="list-group-item deactive">
            <h4 class="list-group-item-heading">{{ contenido.titulo|safe }}</h4>
            <p class="list-group-item-text">{{contenido.fecha_modificacion|safe}}</p>
        </a>
    </div>
{% endfor %}
{% endblock %}

Jayus/JayusApp/templates/logged_out.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrahead %}
  <style>
    .row {
      padding: 100px;
    }
  </style>
{% endblock extrahead %}

{% block sidebar_menu %}{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block main_header %}{% endblock %}

{% block content_container %}

  <p class="alert alert-info">{% trans "Thanks for spending some quality time with the Web site today." %}</p>

  <p><a href="{% url 'home' %}" class="btn btn-primary">Home</a></p>

  <p><a href="{% url 'admin:index' %}" class="btn btn-primary">{% trans 'Log in again' %}</a></p>

{% endblock content_container %}

Jayus/JayusApp/templates/mis_comunidades.html
{% extends "admin/my_custom_index.html" %}

{% block title %}Jayus | Perfil {{usuario.username}}{% endblock %}

{% block content %}
    {% for comunidad in mis_comunidades %}
        <div class="list-group">
          <a href="{% url 'JayusApp.views.comunidad' comunidad.id %}" class="list-group-item deactive">
            <h4 class="list-group-item-heading"> {{comunidad.nombre}}</h4>
            <p class="list-group-item-text">{{ comunidad.descripcion }}</p>
          </a>
        </div>
    {% endfor %}
{% endblock %}

Jayus/JayusApp/templates/registrar_user.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static bootstrap_admin_template_tags %}

{% block extrastyle %}

{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />{% endblock %}
    {% block bodyclass %}
        {{ block.super }} login
    {% endblock %}
{% block nav-global %}

{% endblock %}

{% block branding %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block sidebar_menu %}{% endblock %}

{% block content_container %}

<center style="width:30%; margin: 0 auto !important;">
    <div class="panel panel-primary" style="padding:2%">
      <div class="panel-heading">Registrarse</div>
      <div class="panel-body">
        <form action="{% url 'JayusApp.views.registrar' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_username">Usuario</label>
                </div>
                <div class="col-md-6">
                    {{ form.username }}
                </div>
            </div>
            <div class="row">
                {{ form.username.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_email">Email</label>
                </div>
                <div class="col-md-6">
                    {{ form.email }}
                </div>
            </div>
            <div class="row">
                {{ form.email.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_password1">Contraseña</label>
                </div>
                <div class="col-md-6">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="row">
                {{ form.password1.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_password2">Repetir contraseña</label>
                </div>
                <div class="col-md-6">
                    {{ form.password2}}
                </div>
            </div>
            <div class="row">
                {{ form.password2.errors }}
            </div>

            <div class="row">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>

            <div class="row" style="padding:2%">
                <button class="btn btn-primary" type="submit">Registrar</button>
                <a class="btn btn-default" href="{% url 'JayusApp.views.home' %}"">Cancelar </a>
            </div>
        </form>
      </div>
    </div>
</center>
{% endblock %}

Jayus/JayusApp/templates/validar_user.html
{% extends "admin/my_custom_index.html" %}

{% block content %}

<div class="container">
    <form action="{% url 'JayusApp.views.validar' id %}" method="post">
        {% csrf_token %}
        <div style="display:none">
            {{id}}
        </div>

        <div class="row">
            Ya casi eres un usuario. Por favor haz click en el siguiente
        </div>

        <div class="row" style="padding:2%">
            <button class="btn btn-primary" type="submit">Validar</button>
        </div>
    </form>
</div>

{% endblock %}